name: Build Custom Alpine ISO

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggers

jobs:
  build-alpine:
    runs-on: ubuntu-latest # Default GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Alpine in Docker
        uses: docker://alpine:latest
        with:
          entrypoint: ""
        run: |
          apk add --no-cache alpine-sdk xorriso syslinux genisoimage
          wget https://raw.githubusercontent.com/alpinelinux/aports/master/scripts/mkimage.sh -O /build/mkimage.sh
          chmod +x /build/mkimage.sh
          mkdir -p /build/output
          ./build/mkimage.sh \
            --profile standard \
            --outdir /build/output \
            --arch x86_64 \
            --overlay /build/overlay \
            --packages "chromium openrc"

      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-alpine-iso
          path: /build/output/*.iso