name: Build Custom Alpine ISO

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch: # Allows manual triggers

jobs:
  build-alpine:
    runs-on: ubuntu-latest # Default GitHub-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            alpine:latest \
            sh -c "
              apk add --no-cache alpine-sdk alpine-conf syslinux xorriso squashfs-tools grub grub-efi doas;
              curl -O https://raw.githubusercontent.com/alpinelinux/aports/master/scripts/mkimage.sh;
              chmod +x mkimage.sh;
              mkdir -p output;
              ./mkimage.sh --profile standard --outdir ./output --arch x86_64 --overlay ./overlay --packages 'chromium openrc';
            "
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: custom-alpine-iso
          path: /build/output/*.iso
