name: Build BrowserOS ISO

on:
  workflow_dispatch: # manual trigger

jobs:
  build-alpine:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Fetch Dependencies
        run: ./dependencies.sh
      - name: Build BrowserOS
        run: ./build.sh
      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: browseros
          path: /build/output/*.iso
